# Generated by Django 4.1.4 on 2023-01-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_rename_first_name_order_full_name_remove_order_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
